### ISSUE TITLE
ERSEM docs build failed

### ISSUE THREAD

**Issue by wathen** [pmlmodelling/ersem#12]
Investigate why the ERSEM docs aren't building correctly

**Comment by r4ecology** [comment]
What is the issue? I had problems recently with nctoolkit's docs on readthedocs due to an update to a dependency. This is possibly the same issue

**Comment by wathen** [comment]
This is the error that comes up when I look at the build. I'm guessing it has something to to with the yaml file that sets the path to the `conf.py` 

![Screenshot from 2021-04-28 15-29-02](https://user-images.githubusercontent.com/15614849/116421205-894a9980-a836-11eb-84f2-eadf0df93cde.png)

**Comment by r4ecology** [comment]
Did this only just start happen lately? You could maybe try pinning the version numbers in requirements.txt to see if that fixes anything. It could be a bug in a dependency update

**Comment by jimc101** [comment]
In the readthedocs yaml file, you specify the location of the config file (option configuration). However, the path looks like it is incorrect. It should be `docs` and not `doc`, I think.

**Comment by r4ecology** [comment]
good spot. Do you actually need the configuration path? nctoolkit doesn't, and based on googling just now, readthedocs should be able to find it automatically so long as the readthedocs yaml file is in the root directory of the project

**Comment by wathen** [comment]
The last project I was on you did not need the config path but when I was linking the docs to read the docs it was necessary.
