### ISSUE TITLE
Change rm parameter name in primary_producer.F90

### ISSUE THREAD

**Issue by hpowley** [pmlmodelling/ersem#121]
If rm is assigned >0 in the primary_producer module, it looks like rm is being used in the _set_vertical_movement_ routine twice - once in pelagic base.F90 and once in primary_producer.F90 Tests indicate difference in results if the rm parameter name with primary_producer.F90 is changed and nothing else.

**Comment by wathen** [comment]
@glessin and @hpowley, can you look into this?

**Comment by glessin** [comment]
rm is an optional parameter in initialize_ersem_base subroutine of benthic_base.F90. The call in primary_producer.F90 does not include rm:
call self%initialize_ersem_base(sedimentation=.true.)
Therefore only rm defined is primary_producer.F90 is used, which is set to 0._rk by default.
Case closed.
