### ISSUE TITLE
BGE in bacteria_docdyn.F90

### ISSUE THREAD

**Issue by glessin** [pmlmodelling/ersem#63]
`         IF (netB1.gt.0._rk) THEN
            BGE=netB1/rugB1
         ELSE
            BGE=0._rk
         ENDIF
`
This does not currently carry any functionality apparently?

**Comment by yutiPML** [comment]
BGE (i.e. Bacterial Growth Efficiency) is a diagnostic that Luca used before FABM, however it seems that it is not been properly declared nor registered nor set. I think that the best option could be to actually fix the latter

**Comment by glessin** [comment]
Added diagnostic for bacterial growth efficiency (bgeff) on branch 63_bge, renaming from BGE to avoid confusion with Fortran "bitwise greater than or equal to" function.
