### ISSUE TITLE
Typos/formatting errors on ERSEM areas model page

### ISSUE THREAD

**Issue by hpowley** [pmlmodelling/ersem#93]
There are various typos/ formatting errors on this page, https://ersem.readthedocs.io/en/latest/model_info/description.html,  both in the table and key.  I also suggest that some of the acronyms (especially WEC) are written out in full as people are unlikely to know what it is.

Dale - can you also please add SANH and ACCORD domains to the table

**Comment by glessin** [comment]
Corrected based on https://www.masts.ac.uk/media/4765/nemo-ersem.pdf. Note that this table is out of date (2015) and will be updated in the near future.
