### ISSUE TITLE
Test cases have require_initialization set but lack some initial values

### ISSUE THREAD

**Issue by jornbr** [pmlmodelling/ersem#99]
The current `testcases/fabm-ersem-*.yaml` files have `require_initialization: true` as one of their first lines. This tells FABM that all state variables need to be provided with an initial value in the instance-specific "initialization" sections further down. FABM does not currently enforce this, but this will change in the upcoming v1.5. However, in ERSEM's current testcases the initialization information is incomplete, which will cause them to fail with FABM 1.5. For instance, the following are missing from `fabm-ersem-15.06-L4-ben-docdyn-iop.yaml`:

O3/bioalk
G2/o_deep
ben_nit/G4n

In FABM < 1.5, these are silently initialized to 0, which is likely the desired behaviour here. To support future FABM versions, these initial values can either be added explicitly, or `require_initialization` can be changed to `false`. Either change is fully backwards compatible with FABM < 1.5.

If testing with FABM v1.5 is desired: this functionality is currently in FABM branch `yaml-settings`.

**Comment by jornbr** [comment]
Just to note that this will become an issue with [the upcoming FABM 2.0 release (see fabm-model/fabm#41), due September. It could be a good idea to drop `require_initialization: true` from all ERSEM testcases beforehand, perhaps independent of the usual ERSEM release cycle, to avoid users experiencing issues.

**Comment by wathen** [comment]
Fixed via #115
